// <auto-generated />
using AMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825223626_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMS.Entities.Accession", b =>
                {
                    b.Property<int>("AccessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessionId"));

                    b.Property<string>("AccessionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccessionPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreederOrCollector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CultivarName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DescriptorId")
                        .HasColumnType("integer");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelOfImprovement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LifeForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MyProperty")
                        .HasColumnType("integer");

                    b.Property<string>("PlantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleasedDateFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("integer");

                    b.Property<string>("SiteComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int>("TaxonId")
                        .HasColumnType("integer");

                    b.HasKey("AccessionId");

                    b.HasIndex("DescriptorId");

                    b.HasIndex("TaxonId");

                    b.ToTable("Acessions");
                });

            modelBuilder.Entity("AMS.Entities.AccessionSource", b =>
                {
                    b.Property<int>("AccessionSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessionSourceId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOrgin")
                        .HasColumnType("boolean");

                    b.Property<string>("ProvinceState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceSeq")
                        .HasColumnType("integer");

                    b.HasKey("AccessionSourceId");

                    b.HasIndex("AccessionId");

                    b.ToTable("AccessionSources");
                });

            modelBuilder.Entity("AMS.Entities.Cooperator", b =>
                {
                    b.Property<int>("CooperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CooperatorId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CooperatorId");

                    b.ToTable("Cooperators");
                });

            modelBuilder.Entity("AMS.Entities.Descriptor", b =>
                {
                    b.Property<int>("DescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DescriptorId"));

                    b.Property<int>("AccesssionId")
                        .HasColumnType("integer");

                    b.Property<string>("Cmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Density")
                        .HasColumnType("double precision");

                    b.Property<string>("FireblightRating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstBloomDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FruitFleshOXI")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitLenght")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitShape")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitStemLength")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitStemThick")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitTexture")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("FruitWidth")
                        .HasColumnType("double precision");

                    b.Property<string>("FullBloomDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SeedLength")
                        .HasColumnType("double precision");

                    b.Property<double>("SeedNumber")
                        .HasColumnType("double precision");

                    b.Property<double>("SeedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("SeedShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SeedWidth")
                        .HasColumnType("double precision");

                    b.HasKey("DescriptorId");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("AMS.Entities.FireblightRating", b =>
                {
                    b.Property<int>("FireblightRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FireblightRatingId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<int>("ObservationSeq")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("FireblightRatingId");

                    b.HasIndex("AccessionId");

                    b.ToTable("FireblightRatings");
                });

            modelBuilder.Entity("AMS.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsDistributable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationSelection1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationSelection2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationSelection3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationSelection4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaintenancePolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InventoryId");

                    b.HasIndex("AccessionId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("AMS.Entities.Ipr", b =>
                {
                    b.Property<int>("IprId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IprId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<int>("CooperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("IprType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IprId");

                    b.HasIndex("AccessionId");

                    b.HasIndex("CooperatorId");

                    b.ToTable("Iprs");
                });

            modelBuilder.Entity("AMS.Entities.Narrative", b =>
                {
                    b.Property<int>("NarrativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NarrativeId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<string>("NarrativeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NarrativeId");

                    b.HasIndex("AccessionId");

                    b.ToTable("Narratives");
                });

            modelBuilder.Entity("AMS.Entities.Pedigree", b =>
                {
                    b.Property<int>("PedigreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedigreeId"));

                    b.Property<int>("AccessionId")
                        .HasColumnType("integer");

                    b.Property<string>("CrossMethod")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalFemaleName")
                        .HasColumnType("text");

                    b.Property<string>("ExternalMaleName")
                        .HasColumnType("text");

                    b.Property<int?>("FemaleAccessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaleAccessionId")
                        .HasColumnType("integer");

                    b.HasKey("PedigreeId");

                    b.HasIndex("AccessionId")
                        .IsUnique();

                    b.ToTable("Pedigrees");
                });

            modelBuilder.Entity("AMS.Entities.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("AMS.Entities.Taxon", b =>
                {
                    b.Property<int>("TaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaxonId"));

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaxonId");

                    b.ToTable("Taxons");
                });

            modelBuilder.Entity("AccessionCooperator", b =>
                {
                    b.Property<int>("AccessionsAccessionId")
                        .HasColumnType("integer");

                    b.Property<int>("CooperatorsCooperatorId")
                        .HasColumnType("integer");

                    b.HasKey("AccessionsAccessionId", "CooperatorsCooperatorId");

                    b.HasIndex("CooperatorsCooperatorId");

                    b.ToTable("AccessionCooperator");
                });

            modelBuilder.Entity("AMS.Entities.Accession", b =>
                {
                    b.HasOne("AMS.Entities.Descriptor", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorId");

                    b.HasOne("AMS.Entities.Taxon", null)
                        .WithMany("Accessions")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descriptor");
                });

            modelBuilder.Entity("AMS.Entities.AccessionSource", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany("Sources")
                        .HasForeignKey("AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.FireblightRating", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany("FireblightRatings")
                        .HasForeignKey("AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.Inventory", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany("Inventories")
                        .HasForeignKey("AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.Ipr", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany("IprRecords")
                        .HasForeignKey("AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS.Entities.Cooperator", null)
                        .WithMany("IprRecords")
                        .HasForeignKey("CooperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.Narrative", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany("Narratives")
                        .HasForeignKey("AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.Pedigree", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithOne("Pedigree")
                        .HasForeignKey("AMS.Entities.Pedigree", "AccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessionCooperator", b =>
                {
                    b.HasOne("AMS.Entities.Accession", null)
                        .WithMany()
                        .HasForeignKey("AccessionsAccessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS.Entities.Cooperator", null)
                        .WithMany()
                        .HasForeignKey("CooperatorsCooperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Entities.Accession", b =>
                {
                    b.Navigation("FireblightRatings");

                    b.Navigation("Inventories");

                    b.Navigation("IprRecords");

                    b.Navigation("Narratives");

                    b.Navigation("Pedigree");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AMS.Entities.Cooperator", b =>
                {
                    b.Navigation("IprRecords");
                });

            modelBuilder.Entity("AMS.Entities.Taxon", b =>
                {
                    b.Navigation("Accessions");
                });
#pragma warning restore 612, 618
        }
    }
}
